language: python

branches:
  only:
    - test
    - main

python:
  - "3.10"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y netcat
  - mkdir -p docker/data/cassandra1 docker/data/cassandra2 docker/data/cassandra3
  - docker-compose -f "docker-compose.yaml" up -d --build
  - sleep 5

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev

script:
  - |
    echo "Waiting for Cassandra to become ready..."
    MAX_ATTEMPTS=10
    COMMAND='docker exec cassandra3 cqlsh --debug cassandra3 9042 --execute="DESCRIBE SCHEMA;"'
    COUNT=0
    until OUTPUT=$($COMMAND 2>&1) || [ $COUNT -eq $MAX_ATTEMPTS ]
    do
      echo "$OUTPUT"
      sleep 45
      COUNT=$((COUNT+1))
      echo "Attempt: $COUNT/$MAX_ATTEMPTS"
    done
    if [ $COUNT -eq $MAX_ATTEMPTS ]; then
      echo "Cassandra did not become ready within the expected time. Exiting..."
      exit 1
    fi
    echo "Cassandra is ready!"
  - docker ps
  - docker exec cassandra1 nodetool status
  - pipenv run python scripts/generate_data.py

after_script:
  - docker-compose -f "docker-compose.yaml" down
