version: '3.9'

services:
  cassandra:
    container_name: cassandra1
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - ~/cassandra/docker/data/cassandra1:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=maratos
      - CASSANDRA_LISTEN_ADDRESS=cassandra
      - CASSANDRA_BROADCAST_ADDRESS=172.28.0.2      
    networks:
      test:
        ipv4_address: 172.28.0.2
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE CLUSTER'"]
      interval: 30s
      timeout: 10s
      retries: 3

  cassandra2:
    container_name: cassandra2
    image: cassandra
    depends_on:
      - cassandra
    ports:
      - 9043:9042
    volumes:
      - ~/cassandra/docker/data/cassandra2:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=maratos
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_LISTEN_ADDRESS=172.28.0.3
      - CASSANDRA_BROADCAST_ADDRESS=172.28.0.3      
    networks:
      test:
        ipv4_address: 172.28.0.3
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE CLUSTER'"]
      interval: 30s
      timeout: 10s
      retries: 3

  cassandra3:
    container_name: cassandra3
    image: cassandra
    depends_on:
      - cassandra2    
    ports:
      - 9044:9042
    volumes:
      - ~/cassandra/docker/data/cassandra3:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=maratos
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_LISTEN_ADDRESS=172.28.0.4
      - CASSANDRA_BROADCAST_ADDRESS=172.28.0.4 
    networks:
      test:
        ipv4_address: 172.28.0.4
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE CLUSTER'"]
      interval: 30s
      timeout: 10s
      retries: 3        

networks:
    test:
      ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/24