version: '3.9'

services:
  cassandra1:
    container_name: cassandra1
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - ~/cassandra/docker/data/cassandra1:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=maratos
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1  
    networks:
      test:
        ipv4_address: 172.28.250.2
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE CLUSTER'"]
      interval: 30s
      timeout: 10s
      retries: 3

  cassandra2:
    container_name: cassandra2
    image: cassandra
    depends_on:
      - cassandra
    ports:
      - 9043:9042
    volumes:
      - ~/cassandra/docker/data/cassandra2:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=maratos
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=cassandra2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2     
    networks:
      test:
        ipv4_address: 172.28.250.3
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE CLUSTER'"]
      interval: 30s
      timeout: 10s
      retries: 3

  cassandra3:
    container_name: cassandra3
    image: cassandra
    depends_on:
      - cassandra2    
    ports:
      - 9044:9042
    volumes:
      - ~/cassandra/docker/data/cassandra3:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=maratos
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=cassandra3
      - CASSANDRA_BROADCAST_ADDRESS=cassandra3
    networks:
      test:
        ipv4_address: 172.28.250.4
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE CLUSTER'"]
      interval: 30s
      timeout: 10s
      retries: 3        

networks:
    test:
      ipam:
        driver: default
        config:
          - subnet: 172.28.250.0/24