name: Test

on:
  push:
    branches:
    - test
  pull_request:
    branches:
    - main

jobs:
  prepare:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y netcat

    - name: Create directories for Cassandras clusters
      run: mkdir -p docker/data/cassandra1 docker/data/cassandra2 docker/data/cassandra3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Start containers
      run: docker-compose -f "docker-compose.yaml" up -d --build

    - name: Check Cassandra readiness
      run: |
        echo "Checking Cassandra readiness..."
        MAX_TRIES=20
        COUNTER=0
    
        # This command will try to execute a simple CQL command. If Cassandra is not ready, it will fail.
        # We will try MAX_TRIES times, waiting for 10 seconds between each try.
        until docker exec cassandra1 cqlsh --debug cassandra1 9042 --execute="SELECT now() FROM system.local;" || [ $COUNTER -eq $MAX_TRIES ]; do
          sleep 10
          echo "Waiting for Cassandra to be ready... Try: $COUNTER"
          ((COUNTER++))
        done
    
        if [ $COUNTER -eq $MAX_TRIES ]; then
          echo "Cassandra was not ready after $MAX_TRIES attempts. Exiting..."
          exit 1
        fi
    
        echo "Cassandra is ready!"      

    # - name: Wait for Cassandra
    #   run: |
    #     for i in {1..30}; do
    #       nc -z 127.0.0.1 9042 && echo Success && exit 0
    #       echo -n .
    #       sleep 1
    #     done
    #     echo Failed waiting for Cassandra && exit 1

    # - name: Wait for 30 seconds
    #   run: sleep 120
    # - name: Wait for 30 seconds
    #   run: docker exec cassandra1 cqlsh --debug cassandra1 9042 --execute="use somekeyspace;"      

    - name: Docker info
      run: docker ps

    - name: Docker info2
      run: docker logs cassandra1
    # - name: Docker info
    #   run: docker exec cassandra1 nodetool status
        
    - name: Run Python script
      run: pipenv run python scripts/generate_data.py

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
